name: Little Sweet Photo
favicon: null
layout_spectrum: 0.76004
typography_spectrum: 0.48358
title: Little Sweet Photo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#fefef4'
    - '#494e53'
    - '#fb77b4'
    - '#59aa38'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
