name: Little Sweet Photo
favicon: null
layout_spectrum: 0.76004
typography_spectrum: 0.48358
title: Little Sweet Photo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e4ed'
    - '#0a0504'
    - '#fb2327'
    - '#43611d'
    - '#9aa23d'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
