name: Little Sweet Photo
favicon: null
layout_spectrum: 0.8746272325515747
typography_spectrum: 0.4046183943282813
title: Little Sweet Photo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.490714626153931
  lightness: 0.5657000772189349
  saturation: 0.5092404494062066
  rhythmicContrast: 0.6007961423601955
purpose: []
